"""FastAPI dependency injection for database and auth."""

import re
import time
from typing import AsyncGenerator
from urllib.parse import urlparse

import markdown as md_lib
from fastapi import Depends, HTTPException, Request, status
from fastapi.templating import Jinja2Templates
from markupsafe import Markup, escape
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.db.connection import AsyncSessionLocal

# Shared Jinja2Templates instance
templates = Jinja2Templates(directory="src/templates")


# Allowlist-based neutralization of dangerous URL schemes in
# markdown-generated href/src attributes. Browsers strip ASCII control
# characters (tab/newline/CR/...) from a URL before resolving its scheme,
# so an embedded control char (e.g. "java\nscript:") bypasses a denylist
# yet still executes. We strip control chars first, then allow ONLY a
# small set of safe schemes; any other scheme's value becomes "#".
_HREF_SRC_RE = re.compile(r'((?:href|src)=")([^"]*)(")', re.IGNORECASE)
_URL_CONTROL_CHARS_RE = re.compile(r"[\x00-\x1f]")
_URL_WHITESPACE_RE = re.compile(r"\s")
_SAFE_URL_SCHEMES = frozenset({"http", "https", "mailto", ""})


def _sanitize_md_url(match: re.Match[str]) -> str:
    """Neutralize a markdown href/src whose URL scheme is not allowed."""
    prefix, url, suffix = match.group(1), match.group(2), match.group(3)
    cleaned = _URL_CONTROL_CHARS_RE.sub("", url)
    # Detect the scheme on a whitespace-stripped copy: browsers ignore
    # embedded tab/newline/CR, and markdown expands tabs to spaces, so
    # "java\tscript:" / "java\nscript:" must resolve to "javascript:".
    probe = _URL_WHITESPACE_RE.sub("", cleaned)
    try:
        scheme = urlparse(probe).scheme.lower()
    except ValueError:
        scheme = None
    if scheme not in _SAFE_URL_SCHEMES:
        return f"{prefix}#{suffix}"
    return f"{prefix}{cleaned}{suffix}"


def md_filter(text: str | None) -> Markup:
    """Convert markdown text to safe HTML.

    Escapes raw HTML first to prevent XSS, then converts markdown
    syntax to HTML tags. Finally, href/src attributes generated by
    markdown are passed through an allowlist so only safe URL schemes
    (http, https, mailto, relative paths and #anchors) survive; any
    other scheme is replaced with "#".
    """
    if not text:
        return Markup("")
    escaped = str(escape(text))
    html = md_lib.markdown(escaped, extensions=["nl2br"])
    html = _HREF_SRC_RE.sub(_sanitize_md_url, html)
    return Markup(html)


templates.env.filters["md"] = md_filter


class AuthenticationRequired(Exception):  # noqa: N818
    """Exception raised when authentication is required."""

    def __init__(self, redirect_url: str = "/login"):
        self.redirect_url = redirect_url
        super().__init__("Authentication required")


async def get_db_session() -> AsyncGenerator[AsyncSession, None]:
    """
    Provide database session for request scope.

    Yields:
        AsyncSession: Database session with transaction handling.
    """
    async with AsyncSessionLocal() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise
        finally:
            await session.close()


async def get_current_user(
    request: Request,
    db: AsyncSession = Depends(get_db_session),
):
    """
    Get current user from session.

    Args:
        request: FastAPI Request object
        db: Database session

    Returns:
        User: User model instance

    Raises:
        HTTPException: If not authenticated
    """
    from src.models.user import User

    # Get user_id from session
    user_id = request.session.get("user_id")

    # Defensive: touch session to force cookie refresh
    # Ensures itsdangerous timestamp is updated on every request
    if user_id:
        request.session["_refreshed_at"] = int(time.time())

    if not user_id:
        raise AuthenticationRequired(redirect_url="/login")

    # Query user from database
    result = await db.execute(select(User).where(User.id == user_id))
    user = result.scalar_one_or_none()

    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="User not found",
        )

    return user


async def get_admin_user(
    request: Request,
    db: AsyncSession = Depends(get_db_session),
):
    """
    Get current user and verify admin role.

    Args:
        request: FastAPI Request object
        db: Database session

    Returns:
        User: User model instance with admin role

    Raises:
        HTTPException: If not authenticated or not admin
    """
    user = await get_current_user(request, db)
    if not user.is_admin:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Admin access required",
        )
    return user
